apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cnpg
  namespace: flux-system
spec:
  targetNamespace: base-system
  path: kubernetes/apps/base-system/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cnpg
      namespace: base-system
  interval: 15m
  retryInterval: 1m
  timeout: 10m