apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: development
  annotations:
    # load-balancer.hetzner.cloud/network-zone
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/network-zone: eu-central
#    load-balancer.hetzner.cloud/name: cpn
#    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "167.233.11.229"
  externalTrafficPolicy: Local


#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: dev.masterbpro.ru
#  namespace: istio-system
#spec:
#  secretName: dev.masterbpro.ru-tls
#  dnsNames:
#    - dev.masterbpro.ru
#  issuerRef:
#    name: production-cluster-issuer
#    kind: ClusterIssuer
#    group: cert-manager.io
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: main-gw
#  namespace: development
#spec:
#  selector:
#    istio: ingress
#  servers:
#    - port:
#        number: 80
#        name: http
#        protocol: HTTP
#      hosts:
#        - dev.masterbpro.ru
#      tls:
#        httpsRedirect: true
#    - port:
#        number: 443
#        name: https
#        protocol: HTTPS
#      hosts:
#        - dev.masterbpro.ru
#      tls:
#        credentialName: dev.masterbpro.ru-tls
#        mode: SIMPLE
#---
#apiVersion: networking.istio.io/v1beta1
#kind: DestinationRule
#metadata:
#  name: main-dr
#spec:
#  host: main
#  subsets:
#    - name: v1
#      labels:
#        app: main
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: main-vr
#  namespace: development
#spec:
#  hosts:
#    - dev.masterbpro.ru
#  gateways:
#    - main-gw
#  http:
#    - match:
#        - uri:
#            prefix: /
#      route:
#        - destination:
#            host: main
#            port:
#              number: 8000
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: main
#  namespace: development
#spec:
#  selector:
#    app: main
#  ports:
#    - name: http-8000
#      port: 8000
#      targetPort: 80
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: main
#  namespace: development
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: main
#  template:
#    metadata:
#      labels:
#        app: main
#    spec:
#      containers:
#        - name: whoami-container
#          image: containous/whoami