apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hccm
  namespace: &ns kube-system
spec:
  releaseName: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: "1.20.1"
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  interval: 15m
