apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cilium
  namespace: &ns kube-system
spec:
  releaseName: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: *app
      version: "1.15.2"
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  interval: 15m
