apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vm
  namespace: flux-system
spec:
  targetNamespace: observability
  path: kubernetes/apps/observability/vm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vm
      namespace: observability
  interval: 15m
  retryInterval: 1m
  timeout: 10m