apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kiali
  namespace: &ns istio-system
spec:
  releaseName: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: kiali-server
      version: "1.78.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 15m
  values:
    istio_namespace: *ns

    auth:
      strategy: "anonymous"

    deployment:
      replicas: 1

    external_services:
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: ""
