apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kiali
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-base
    - name: cluster-apps-istiod
  targetNamespace: istio-system
  path: kubernetes/apps/istio-system/kiali/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kiali
      namespace: istio-system
  interval: 15m
  retryInterval: 1m
  timeout: 10m