apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vm
  namespace: &ns observability
spec:
  releaseName: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.33.*"
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
  interval: 15m
